version: "3.4"

services:
  clinic.webapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=masoud
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/clinicapp.pfx
    ports:
      - "80"
      - "443"
    volumes:
      # Windows volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # - ${APPSOURCEPATH}/Clinic/Clinic.WebApplication/wwwroot/Administrators/assets/images:/root/app/Clinic.WebApplication/wwwroot/Administrators/assets/images
      # - ${APPSOURCEPATH}/Clinic/Clinic.WebApplication/Logs:/app/Logs
      # Linux volumes:
      - ${HOME}/.aspnet/https:/https/
      - ${HOME}/ClinicWebApp/Clinic/Clinic.WebApplication/wwwroot/Administrators/assets/images:/app/wwwroot/Administrators/assets/images
      - ${HOME}/ClinicWebApp/Clinic/Clinic.WebApplication/Logs:/app/Logs
    depends_on:
      - mssqlserver
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    container_name: mssqldatabase
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Masoud&7559"
      MSSQL_PID: Express
      TZ: "Asia/Tehran"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
