version: "3.4"

services:
  clinic.webapplication:
    image: urmiaking/clinic-image:latest
    container_name: clinicwebapplication
    build:
      context: .
      dockerfile: Clinic.WebApplication/Dockerfile
